services:

  db:
    image: postgres:16
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 60s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080

  habit_tracker:
    build: .
    env_file:
      - ./env/db_env.env
    ports:
      - 3000:8000
    depends_on:
      - db

volumes:
  pgdata: